//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomBookings
    {
        [Display(Name = "Номер бронирования")]
        public int BookingId { get; set; }
        [Display(Name = "ФИО")]
        public string CustomerName { get; set; }
        [Display(Name = "Телефон")]
        public string CustomerNumber { get; set; }
        [Display(Name = "Адрес")]
        public string CustomerAdress { get; set; }
        [Display(Name = "Дата заезда")]
        public System.DateTime BookingFrom { get; set; }
        [Display(Name = "Дата выезда")]
        public System.DateTime BookingTo { get; set; }
        [Display(Name = "Номер комнаты")]
        public int AssignRoomId { get; set; }
        [Display(Name = "Ночей")]
        public int NoOfMembers { get; set; }
        [Display(Name = "Итоговая стоимость")]
        public decimal TotalAmount { get; set; }
        [Display(Name = "Тип оплаты")]
        public Nullable<int> PaymentTypeId { get; set; }
        [Display(Name = "Почта")]
        public string CustomerEmail { get; set; }
        [Display(Name = "Доп. услуги")]
        public Nullable<int> ServiceId { get; set; }
        [Display(Name = "Гость 1")]
        public string CustomerName1 { get; set; }
        [Display(Name = "Гость 2")]
        public string CustomerName2 { get; set; }
        [Display(Name = "Гость 3")]
        public string CustomerName3 { get; set; }
        [Display(Name = "Комментарии")]
        public string Comments { get; set; }
        [Display(Name = "Статус")]
        public Nullable<int> Confirmed { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Services Services { get; set; }
    }
}
