//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTEL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rooms
    {
        [Display(Name = "Id комнаты")]
        public int RoomId { get; set; }
        [Display(Name = "Номер комнаты")]
        public string RoomNumber { get; set; }
        [Display(Name = "Стоимость")]
        public int RoomPrice { get; set; }
        [Display(Name = "Тип комнаты")]
        public int RoomTypeId { get; set; }
        [Display(Name = "Вместимость")]
        public int RoomCapacity { get; set; }
        [Display(Name = "Описание")]
        public string RoomDescription { get; set; }
        [Display(Name = "Фото 1")]
        public byte[] RoomImage1 { get; set; }
        [Display(Name = "Фото 2")]
        public byte[] RoomImage2 { get; set; }
        [Display(Name = "Фото 3")]
        public byte[] RoomImage3 { get; set; }
        [Display(Name = "Фото 4")]
        public byte[] RoomImage4 { get; set; }
        [Display(Name = "Фото 5")]
        public byte[] RoomImage5 { get; set; }
        [Display(Name = "Площадь")]
        public Nullable<int> Square { get; set; }
    
        public virtual RoomTypes RoomTypes { get; set; }
    }
}
